name = "EquiVM"
version = "0.1.0"
# defaultTargets = ["evmlean"] this currently does no correspond to anything
defaultTargets = ["Solm"]

[[lean_lib]]
name = "EquiVM"

[[lean_lib]]
name = "EVM"

[[lean_lib]]
name = "ABI"

[[lean_lib]]
name = "Solm"

[[lean_lib]]
name = "Examples"
globs = ["Examples.+"]

[[lean_lib]]
name = "Reasoning"
globs = ["Reasoning.+"]

[[lean_lib]]
name = "Proofs"
globs = ["Proofs.+"]

[[lean_lib]]
name = "Benchmarks"
globs = ["Benchmarks.+"]

[[lean_lib]]
name = "Tools"
globs = ["Tools.+"]

# [[lean_exe]]
# name = "equivm"
# root = "EquiVM"

[[require]]
name = "evmlean"
git = "https://github.com/lefterislazar/EVMLean.git"
rev = "step_semantics"
