import Examples.Precompiles.Modexp.MultiLimbMontgomerySOSFull
import Examples.Precompiles.Modexp.MultiLimbMontgomerySOSContract
import Examples.Precompiles.Modexp.MultiLimbMontgomerySOSFunctionContract
import Examples.Precompiles.Modexp.MultiLimbExponentArithmeticContract
import Examples.Precompiles.Modexp.MultiLimbOddConversionContract
import Examples.Precompiles.Modexp.MultiLimbOddCompareContract
import Examples.Precompiles.Modexp.MultiLimbOddBaseConversionContract
import Examples.Precompiles.Modexp.MultiLimbOddBranchContract
import Examples.Precompiles.Modexp.MultiLimbOddConversionSemantic
import Examples.Precompiles.Modexp.MultiLimbSchoolbookRemContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookTrimContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDivisorTrimContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookShortContract
import Examples.Precompiles.Modexp.MultiLimbDiv512Contract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookSingleContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookKnuthSetupContract
import Examples.Precompiles.Modexp.MultiLimbClzSemantic
import Examples.Precompiles.Modexp.MultiLimbSchoolbookNormalizationContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDivisionContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDivisionSemantic
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDenormalizationContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDenormalizationSemantic

/-! # Executable and semantic SOS Montgomery verification

This public aggregation module exposes the full data-dependent SOS selector and exact-gas
execution theorem together with the square-construction and Montgomery-reduction semantics.
-/
