import Examples.Precompiles.Modexp.MultiLimbSchoolbookDenormalizationContract
import Examples.Precompiles.Modexp.MultiLimbSchoolbookDivisionSemantic
import Examples.Precompiles.Modexp.MultiLimbSchoolbookNormalizationSemantic

/-!
# Pure semantics of normalized remainder extraction

The generated bytecode shifts each normalized little-endian limb right and fills its high bits
from the next limb.  This module proves that the complete list operation is ordinary natural
division by the normalization factor.
-/

open Ethereum Reasoning.Theory

namespace Modexp.MultiLimbSchoolbookDenormalizationSemantic

open Modexp.MultiLimbSchoolbookDenormalization
open Modexp.MultiLimbSchoolbookNormalization
open Modexp.MultiLimbSchoolbookNormalizationSemantic

set_option maxRecDepth 50000
set_option maxHeartbeats 0

/-- Source-order pure model of the normalized remainder loop. -/
def denormalizeWords (shift : Nat) : List UInt256 → List UInt256
  | [] => []
  | word :: words =>
      (match words with
        | [] => denormalizedLowWord word shift
        | next :: _ => denormalizedWord word next shift) ::
        denormalizeWords shift words

@[simp] theorem denormalizeWords_length (shift : Nat) (words : List UInt256) :
    (denormalizeWords shift words).length = words.length := by
  induction words with
  | nil => rfl
  | cons word words ih =>
      simp [denormalizeWords, ih]

private theorem wordBase_eq_pow : UInt256.size = 2 ^ 256 := by
  norm_num [UInt256.size]

private theorem pow_shift_dvd_wordBase {shift : Nat} (hshift : shift ≤ 256) :
    2 ^ shift ∣ UInt256.size := by
  rw [wordBase_eq_pow]
  exact Nat.pow_dvd_pow 2 hshift

theorem denormalizedLowWord_toNat (word : UInt256) (shift : Nat)
    (hshift : shift < 256) :
    (denormalizedLowWord word shift).toNat = word.toNat / 2 ^ shift := by
  unfold denormalizedLowWord
  have hshiftWord : shift < UInt256.size := lt_trans hshift (by decide)
  have hshiftToNat : (UInt256.ofNat shift).toNat < 256 := by
    rw [UInt256.toNat_ofNat_of_lt hshiftWord]
    exact hshift
  rw [shiftRight_toNat_of_lt256 _ _ hshiftToNat,
    UInt256.toNat_ofNat_of_lt hshiftWord]

private theorem shiftHigh_toNat (word : UInt256) (shift : Nat)
    (hshiftPos : 0 < shift) (hshift : shift < 256) :
    (word.shiftLeft (UInt256.ofNat (256 - shift))).toNat =
      (word.toNat % 2 ^ shift) * 2 ^ (256 - shift) := by
  have hcomplement : 256 - shift < 256 := by omega
  rw [ushl_ofNat_toNat word (256 - shift) hcomplement, Nat.shiftLeft_eq]
  rw [wordBase_eq_pow]
  have hfactor : 2 ^ 256 = 2 ^ shift * 2 ^ (256 - shift) := by
    rw [← Nat.pow_add, Nat.add_sub_of_le hshift.le]
  rw [hfactor, Nat.mul_mod_mul_right]

theorem denormalizedWord_toNat (word next : UInt256) (shift : Nat)
    (hshiftPos : 0 < shift) (hshift : shift < 256) :
    (denormalizedWord word next shift).toNat =
      word.toNat / 2 ^ shift + (next.toNat % 2 ^ shift) * 2 ^ (256 - shift) := by
  have hlow := denormalizedLowWord_toNat word shift hshift
  have hhigh := shiftHigh_toNat next shift hshiftPos hshift
  have hlowBound : word.toNat / 2 ^ shift < 2 ^ (256 - shift) := by
    rw [Nat.div_lt_iff_lt_mul (by positivity)]
    calc
      word.toNat < UInt256.size := word.val.isLt
      _ = 2 ^ (256 - shift) * 2 ^ shift := by
        rw [wordBase_eq_pow, ← Nat.pow_add]
        congr 1
        omega
  have hor := nat_lor_shift_add (word.toNat / 2 ^ shift)
    (next.toNat % 2 ^ shift) (256 - shift) hlowBound
  unfold denormalizedWord
  rw [u256_lor_toNat, hlow, hhigh, hor]
  apply Nat.mod_eq_of_lt
  have hnextMod : next.toNat % 2 ^ shift < 2 ^ shift :=
    Nat.mod_lt _ (by positivity)
  have hnextModSucc : next.toNat % 2 ^ shift + 1 ≤ 2 ^ shift := by omega
  calc
    word.toNat / 2 ^ shift + (next.toNat % 2 ^ shift) * 2 ^ (256 - shift) <
        2 ^ (256 - shift) + (next.toNat % 2 ^ shift) * 2 ^ (256 - shift) := by
          exact Nat.add_lt_add_right hlowBound _
    _ = (next.toNat % 2 ^ shift + 1) * 2 ^ (256 - shift) := by ring
    _ ≤ 2 ^ shift * 2 ^ (256 - shift) :=
      Nat.mul_le_mul_right _ hnextModSucc
    _ = UInt256.size := by
      rw [wordBase_eq_pow, ← Nat.pow_add]
      congr 1
      omega

private theorem radixCons_div
    (low tail shift : Nat) (hshift : shift ≤ 256) :
    (low + UInt256.size * tail) / 2 ^ shift =
      low / 2 ^ shift + 2 ^ (256 - shift) * tail := by
  have hdvd : 2 ^ shift ∣ UInt256.size := pow_shift_dvd_wordBase hshift
  have hdvdTail : 2 ^ shift ∣ UInt256.size * tail :=
    dvd_mul_of_dvd_left hdvd tail
  rw [Nat.add_div_of_dvd_left hdvdTail]
  have hbaseDiv : UInt256.size / 2 ^ shift = 2 ^ (256 - shift) := by
    rw [wordBase_eq_pow]
    have hfactor : 2 ^ 256 = 2 ^ shift * 2 ^ (256 - shift) := by
      rw [← Nat.pow_add, Nat.add_sub_of_le hshift]
    rw [hfactor, Nat.mul_div_cancel_left _ (by positivity : 0 < 2 ^ shift)]
  calc
    low / 2 ^ shift + UInt256.size * tail / 2 ^ shift =
        low / 2 ^ shift + tail * (UInt256.size / 2 ^ shift) := by
          rw [Nat.mul_comm UInt256.size tail, Nat.mul_div_assoc tail hdvd]
    _ = low / 2 ^ shift + 2 ^ (256 - shift) * tail := by
      rw [hbaseDiv, Nat.mul_comm tail]

/-- Cross-limb shifting of an arbitrary little-endian list is exact natural division by the
normalization factor. -/
theorem denormalizeWords_toNat (words : List UInt256) (shift : Nat)
    (hshiftPos : 0 < shift) (hshift : shift < 256) :
    Modexp.wordLimbsToNat (denormalizeWords shift words) =
      Modexp.wordLimbsToNat words / 2 ^ shift := by
  induction words with
  | nil => simp [denormalizeWords, Modexp.wordLimbsToNat]
  | cons word words ih =>
      cases words with
      | nil =>
          simpa [denormalizeWords, Modexp.wordLimbsToNat] using
            denormalizedLowWord_toNat word shift hshift
      | cons next rest =>
          have hword := denormalizedWord_toNat word next shift hshiftPos hshift
          have htail := radixCons_div next.toNat (Modexp.wordLimbsToNat rest) shift hshift.le
          have hwhole := radixCons_div word.toNat
            (next.toNat + UInt256.size * Modexp.wordLimbsToNat rest) shift hshift.le
          have hbase : UInt256.size = 2 ^ shift * 2 ^ (256 - shift) := by
            rw [wordBase_eq_pow, ← Nat.pow_add, Nat.add_sub_of_le hshift.le]
          have hsplit := Nat.mod_add_div next.toNat (2 ^ shift)
          have hsplitScaled := congrArg (fun n => 2 ^ (256 - shift) * n) hsplit
          simp only [denormalizeWords, Modexp.wordLimbsToNat] at ih ⊢
          rw [hword, ih, hwhole, htail, hbase]
          ring_nf at hsplitScaled ⊢
          omega

theorem storeRemainderWord_size_eq
    (mem : ByteArray) (rem value : UInt256) (index : Nat)
    (hwrite : (arrayAddress rem index).toNat + 32 ≤ mem.size) :
    (storeRemainderWord mem rem index value).size = mem.size := by
  simpa only [storeRemainderWord, MultiLimbSchoolbookSingle.storeQuotient,
    arrayAddress] using
    MultiLimbSchoolbookSingle.storeQuotient_size_eq mem rem index value hwrite

theorem arrayWord_storeRemainder_self
    (mem : ByteArray) (aw rem value : UInt256) (index : Nat)
    (hawFit : aw.toNat * 32 < UInt256.size)
    (hwrite : (arrayAddress rem index).toNat + 32 ≤ mem.size)
    (hactive : (arrayAddress rem index).toNat + 32 ≤ 32 * aw.toNat) :
    arrayWord (storeRemainderWord mem rem index value) aw rem index = value := by
  simpa only [storeRemainderWord, MultiLimbSchoolbookSingle.storeQuotient,
    arrayWord, arrayAddress] using
    MultiLimbSchoolbookSingle.arrayWord_storeQuotient_self mem aw rem value index hawFit
      hwrite hactive

theorem arrayWord_storeRemainder_below
    (mem : ByteArray) (aw source rem value : UInt256)
    (sourceIndex storeIndex : Nat)
    (hwrite : (arrayAddress rem storeIndex).toNat + 32 ≤ mem.size)
    (hbelow : (arrayAddress source sourceIndex).toNat + 32 ≤
      (arrayAddress rem storeIndex).toNat) :
    arrayWord (storeRemainderWord mem rem storeIndex value) aw source sourceIndex =
      arrayWord mem aw source sourceIndex := by
  simpa only [storeRemainderWord, MultiLimbSchoolbookSingle.storeQuotient,
    arrayWord, arrayAddress] using
    MultiLimbSchoolbookSingle.arrayWord_storeQuotient_eq mem aw source rem sourceIndex
      storeIndex value hwrite hbelow

theorem arrayWord_storeRemainder_above
    (mem : ByteArray) (aw source rem value : UInt256)
    (sourceIndex storeIndex : Nat)
    (hwrite : (arrayAddress rem storeIndex).toNat + 32 ≤ mem.size)
    (habove : (arrayAddress rem storeIndex).toNat + 32 ≤
      (arrayAddress source sourceIndex).toNat) :
    arrayWord (storeRemainderWord mem rem storeIndex value) aw source sourceIndex =
      arrayWord mem aw source sourceIndex := by
  unfold arrayWord MultiLimbSchoolbookSingle.arrayWord
    MultiLimbSchoolbookShort.arrayWord MultiLimbOddCompare.loadedWord
  simpa only [storeRemainderWord, MultiLimbSchoolbookSingle.storeQuotient,
    arrayAddress] using
    MultiLimbSchoolbookSingle.arrayHeader_storeQuotient_eq_above mem aw rem
      (MultiLimbSchoolbookSingle.arrayAddress source sourceIndex) storeIndex value hwrite habove

/-- Later denormalization writes preserve a wholly lower earlier remainder word. -/
theorem denormalizeRange_preserves_arrayWord_below
    (aw readArray u rem : UInt256) (shift sourceIndex index count : Nat)
    (mem : ByteArray)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (hbelow : ∀ j, j < count ->
      (arrayAddress readArray sourceIndex).toNat + 32 ≤
        (arrayAddress rem (index + j)).toNat) :
    arrayWord (denormalizeRange aw u rem shift index count mem).memory aw
        readArray sourceIndex =
      arrayWord mem aw readArray sourceIndex := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          let word := arrayWord mem aw u index
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          exact arrayWord_storeRemainder_below mem aw readArray rem
            (denormalizedLowWord word shift) sourceIndex index hheadWrite
            (by simpa using hbelow 0 (by omega))
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have hfirst := arrayWord_storeRemainder_below mem aw readArray rem low sourceIndex
            index hheadWrite (by simpa using hbelow 0 (by omega))
          have hsecond := arrayWord_storeRemainder_below lowMem aw readArray rem output
            sourceIndex index hsecondWrite (by simpa using hbelow 0 (by omega))
          have htail := ih (index + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hbelow (j + 1) (by omega))
          change arrayWord
            (denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory aw
              readArray sourceIndex = _
          exact htail.trans (hsecond.trans hfirst)

/-- Denormalization stores also preserve every source word wholly above the destination range. -/
theorem denormalizeRange_preserves_arrayWord_above
    (aw readArray u rem : UInt256) (shift sourceIndex index count : Nat)
    (mem : ByteArray)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (habove : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤
        (arrayAddress readArray sourceIndex).toNat) :
    arrayWord (denormalizeRange aw u rem shift index count mem).memory aw
        readArray sourceIndex =
      arrayWord mem aw readArray sourceIndex := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          let word := arrayWord mem aw u index
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          exact arrayWord_storeRemainder_above mem aw readArray rem
            (denormalizedLowWord word shift) sourceIndex index hheadWrite
            (by simpa using habove 0 (by omega))
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have hfirst := arrayWord_storeRemainder_above mem aw readArray rem low sourceIndex
            index hheadWrite (by simpa using habove 0 (by omega))
          have hsecond := arrayWord_storeRemainder_above lowMem aw readArray rem output
            sourceIndex index hsecondWrite (by simpa using habove 0 (by omega))
          have htail := ih (index + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                habove (j + 1) (by omega))
          change arrayWord
            (denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory aw
              readArray sourceIndex = _
          exact htail.trans (hsecond.trans hfirst)

/-- Denormalization preserves a complete raw word below every destination store. -/
theorem denormalizeRange_preserves_read_below
    (aw u rem : UInt256) (shift read index count : Nat) (mem : ByteArray)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (hbelow : ∀ j, j < count ->
      read + 32 ≤ (arrayAddress rem (index + j)).toNat) :
    (denormalizeRange aw u rem shift index count mem).memory.readWithPadding read 32 =
      mem.readWithPadding read 32 := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          let word := arrayWord mem aw u index
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          change ((denormalizedLowWord word shift).toByteArray.write 0 mem
            (arrayAddress rem index).toNat 32).readWithPadding read 32 = _
          exact write32_read_below (denormalizedLowWord word shift).toByteArray mem
            (arrayAddress rem index).toNat read (by rw [toByteArray_size])
            (by omega) (by simpa using hbelow 0 (by omega))
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have hfirst : lowMem.readWithPadding read 32 = mem.readWithPadding read 32 := by
            dsimp only [lowMem]
            unfold storeRemainderWord
            exact write32_read_below low.toByteArray mem (arrayAddress rem index).toNat read
              (by rw [toByteArray_size]) (by omega) (by simpa using hbelow 0 (by omega))
          have hsecond : nextMem.readWithPadding read 32 =
              lowMem.readWithPadding read 32 := by
            dsimp only [nextMem]
            unfold storeRemainderWord
            exact write32_read_below output.toByteArray lowMem
              (arrayAddress rem index).toNat read (by rw [toByteArray_size])
              (by omega) (by simpa using hbelow 0 (by omega))
          have htail := ih (index + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hbelow (j + 1) (by omega))
          change ((denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory
              ).readWithPadding read 32 = _
          exact htail.trans (hsecond.trans hfirst)

/-- Denormalization preserves a padded raw word wholly above every destination store. -/
theorem denormalizeRange_preserves_read_above
    (aw u rem : UInt256) (shift read index count : Nat) (mem : ByteArray)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (habove : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ read) :
    (denormalizeRange aw u rem shift index count mem).memory.readWithPadding read 32 =
      mem.readWithPadding read 32 := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          let word := arrayWord mem aw u index
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          change ((denormalizedLowWord word shift).toByteArray.write 0 mem
            (arrayAddress rem index).toNat 32).readWithPadding read 32 = _
          exact write32_read_above_padded (denormalizedLowWord word shift).toByteArray mem
            (arrayAddress rem index).toNat read (by rw [toByteArray_size]) hheadWrite
            (by simpa using habove 0 (by omega))
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have hfirst : lowMem.readWithPadding read 32 = mem.readWithPadding read 32 := by
            dsimp only [lowMem]
            unfold storeRemainderWord
            exact write32_read_above_padded low.toByteArray mem
              (arrayAddress rem index).toNat read (by rw [toByteArray_size]) hheadWrite
              (by simpa using habove 0 (by omega))
          have hsecond : nextMem.readWithPadding read 32 =
              lowMem.readWithPadding read 32 := by
            dsimp only [nextMem]
            unfold storeRemainderWord
            exact write32_read_above_padded output.toByteArray lowMem
              (arrayAddress rem index).toNat read (by rw [toByteArray_size]) hsecondWrite
              (by simpa using habove 0 (by omega))
          have htail := ih (index + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                habove (j + 1) (by omega))
          change ((denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory
              ).readWithPadding read 32 = _
          exact htail.trans (hsecond.trans hfirst)

/-- In-bounds denormalization stores preserve the concrete byte-array extent. -/
theorem denormalizeRange_size_eq
    (aw u rem : UInt256) (shift index count : Nat) (mem : ByteArray)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size) :
    (denormalizeRange aw u rem shift index count mem).memory.size = mem.size := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          exact storeRemainderWord_size_eq mem rem
            (denormalizedLowWord (arrayWord mem aw u index) shift) index
            (by simpa using hwrite 0 (by omega))
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have htail := ih (index + 1) nextMem (by
            intro j hj
            rw [hnextSize]
            simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
              hwrite (j + 1) (by omega))
          exact htail.trans hnextSize

/-- The exact operational denormalization recurrence leaves the pure cross-limb right shift in
the final concrete remainder slice. -/
theorem denormalizeRange_finalSlice
    (aw u rem : UInt256) (shift index count : Nat) (mem : ByteArray)
    (hawFit : aw.toNat * 32 < UInt256.size)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (hactive : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ 32 * aw.toNat)
    (hremBelowSource : ∀ i j, i < count -> j < count ->
      (arrayAddress rem (index + i)).toNat + 32 ≤
        (arrayAddress u (index + j)).toNat)
    (hordered : ∀ i j, i < j -> j < count ->
      (arrayAddress rem (index + i)).toNat + 32 ≤
        (arrayAddress rem (index + j)).toNat) :
    arrayReadWords (denormalizeRange aw u rem shift index count mem).memory aw rem
        index count =
      denormalizeWords shift (arrayReadWords mem aw u index count) := by
  induction count generalizing index mem with
  | zero => rfl
  | succ count ih =>
      cases count with
      | zero =>
          let word := arrayWord mem aw u index
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hheadActive : (arrayAddress rem index).toNat + 32 ≤ 32 * aw.toNat := by
            simpa using hactive 0 (by omega)
          have hself := arrayWord_storeRemainder_self mem aw rem
            (denormalizedLowWord word shift) index hawFit hheadWrite hheadActive
          simpa only [denormalizeRange, arrayReadWords, denormalizeWords] using
            congrArg (fun value => [value]) hself
      | succ count =>
          let word := arrayWord mem aw u index
          let low := denormalizedLowWord word shift
          let lowMem := storeRemainderWord mem rem index low
          let next := arrayWord lowMem aw u (index + 1)
          let output := denormalizedWord word next shift
          let nextMem := storeRemainderWord lowMem rem index output
          have hheadWrite : (arrayAddress rem index).toNat + 32 ≤ mem.size := by
            simpa using hwrite 0 (by omega)
          have hheadActive : (arrayAddress rem index).toNat + 32 ≤ 32 * aw.toNat := by
            simpa using hactive 0 (by omega)
          have hlowSize : lowMem.size = mem.size :=
            storeRemainderWord_size_eq mem rem low index hheadWrite
          have hsecondWrite : (arrayAddress rem index).toNat + 32 ≤ lowMem.size := by
            rw [hlowSize]
            exact hheadWrite
          have hnextSize : nextMem.size = mem.size := by
            rw [storeRemainderWord_size_eq lowMem rem output index hsecondWrite, hlowSize]
          have hnextEq : next = arrayWord mem aw u (index + 1) := by
            exact arrayWord_storeRemainder_above mem aw u rem low (index + 1) index
              hheadWrite (by simpa using hremBelowSource 0 1 (by omega) (by omega))
          have hself : arrayWord nextMem aw rem index = output :=
            arrayWord_storeRemainder_self lowMem aw rem output index hawFit hsecondWrite
              hheadActive
          have hheadPreserved := denormalizeRange_preserves_arrayWord_below aw rem u rem shift
            index (index + 1) (count + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hordered 0 (j + 1) (by omega) (by omega))
          have hsourceLow :
              arrayReadWords lowMem aw u (index + 1) (count + 1) =
                arrayReadWords mem aw u (index + 1) (count + 1) := by
            simpa only [lowMem, storeRemainderWord,
              MultiLimbSchoolbookSingle.storeQuotient] using
              arrayReadWords_storeValue_above mem aw u rem low (index + 1) (count + 1)
                index hheadWrite (by
                  intro j hj
                  simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                    hremBelowSource 0 (j + 1) (by omega) (by omega))
          have hsourceSecond :
              arrayReadWords nextMem aw u (index + 1) (count + 1) =
                arrayReadWords lowMem aw u (index + 1) (count + 1) := by
            simpa only [nextMem, storeRemainderWord,
              MultiLimbSchoolbookSingle.storeQuotient] using
              arrayReadWords_storeValue_above lowMem aw u rem output (index + 1)
                (count + 1) index hsecondWrite (by
                  intro j hj
                  simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                    hremBelowSource 0 (j + 1) (by omega) (by omega))
          have htail := ih (index + 1) nextMem
            (by
              intro j hj
              rw [hnextSize]
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hwrite (j + 1) (by omega))
            (by
              intro j hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 j] using
                hactive (j + 1) (by omega))
            (by
              intro i j hi hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 i, Nat.add_comm 1 j] using
                hremBelowSource (i + 1) (j + 1) (by omega) (by omega))
            (by
              intro i j hij hj
              simpa only [Nat.add_assoc, Nat.add_comm 1 i, Nat.add_comm 1 j] using
                hordered (i + 1) (j + 1) (by omega) (by omega))
          rw [hsourceSecond, hsourceLow] at htail
          change
            arrayWord
                (denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory
                aw rem index ::
              arrayReadWords
                (denormalizeRange aw u rem shift (index + 1) (count + 1) nextMem).memory
                aw rem (index + 1) (count + 1) =
            denormalizedWord word (arrayWord mem aw u (index + 1)) shift ::
              denormalizeWords shift (arrayReadWords mem aw u (index + 1) (count + 1))
          rw [hheadPreserved, hself, htail]
          dsimp only [output]
          rw [hnextEq]

/-- The actual final remainder array produced by the operational recurrence has the normalized
source value divided by `2^shift`. -/
theorem denormalizeRange_finalSlice_toNat
    (aw u rem : UInt256) (shift index count : Nat) (mem : ByteArray)
    (hshiftPos : 0 < shift) (hshift : shift < 256)
    (hawFit : aw.toNat * 32 < UInt256.size)
    (hwrite : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ mem.size)
    (hactive : ∀ j, j < count ->
      (arrayAddress rem (index + j)).toNat + 32 ≤ 32 * aw.toNat)
    (hremBelowSource : ∀ i j, i < count -> j < count ->
      (arrayAddress rem (index + i)).toNat + 32 ≤
        (arrayAddress u (index + j)).toNat)
    (hordered : ∀ i j, i < j -> j < count ->
      (arrayAddress rem (index + i)).toNat + 32 ≤
        (arrayAddress rem (index + j)).toNat) :
    Modexp.wordLimbsToNat
        (arrayReadWords (denormalizeRange aw u rem shift index count mem).memory aw rem
          index count) =
      Modexp.wordLimbsToNat (arrayReadWords mem aw u index count) / 2 ^ shift := by
  rw [denormalizeRange_finalSlice aw u rem shift index count mem hawFit hwrite hactive
    hremBelowSource hordered]
  exact denormalizeWords_toNat (arrayReadWords mem aw u index count) shift hshiftPos hshift

end Modexp.MultiLimbSchoolbookDenormalizationSemantic
