-- Generated by Tools/generate_rdx_blocks.py; do not edit manually.
import Reasoning.SymCheck
import Tools.SymCheck.Fixtures.SymCheckFixtureCode

open Solm ABI Ethereum Ethereum.EVM
open Reasoning.Reach

set_option maxRecDepth 100000
set_option linter.unusedVariables false

namespace SymCheckBranchSmoke

private theorem symcheckCodeMatches :
    symCheckBranchFixtureBytecode = ⟨#[0x57, 0x00, 0x5b, 0x8b, 0x9f, 0x00, 0x5b, 0x56]⟩ := by native_decide

evm_theorem block_0_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 stack_1 : UInt256}
    (hdepth : tail.length + 2 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨0⟩ (stack_0 :: stack_1 :: tail) mem aw rdata acc k C) :=
  (h).withPC (pc' := ⟨0⟩) (by native_decide)

evm_theorem block_0_taken
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 stack_1 : UInt256}
    (hdepth : tail.length + 2 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨0⟩ (stack_0 :: stack_1 :: tail) mem aw rdata acc k C) :=
  fun (hdec : _) (hcondition : _) (hjd : _) =>
    (block_0_body hdepth h).jumpiT hdec hcondition hjd (by omega)

evm_theorem block_0_notTaken
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 stack_1 : UInt256}
    (hdepth : tail.length + 2 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨0⟩ (stack_0 :: stack_1 :: tail) mem aw rdata acc k C) :=
  fun (hdec : _) (hcondition : _) =>
    (block_0_body hdepth h).jumpiNT hdec hcondition (by omega)

evm_theorem block_1_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨1⟩ (tail) mem aw rdata acc k C) :=
  (h).withPC (pc' := ⟨1⟩) (by native_decide)

evm_theorem block_1_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨1⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      stop
    ]

evm_theorem block_2_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 stack_1 stack_2 stack_3 stack_4 stack_5 stack_6 stack_7 stack_8 stack_9 stack_10 stack_11 stack_12 stack_13 stack_14 stack_15 : UInt256}
    (hdepth : tail.length + 16 ≤ 1023)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨2⟩ (stack_0 :: stack_1 :: stack_2 :: stack_3 :: stack_4 :: stack_5 :: stack_6 :: stack_7 :: stack_8 :: stack_9 :: stack_10 :: stack_11 :: stack_12 :: stack_13 :: stack_14 :: stack_15 :: tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      jumpdest,
      dup12Canonical,
      swap16Canonical
    ])).withPC (pc' := ⟨5⟩) (by native_decide)

evm_theorem block_2_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 stack_1 stack_2 stack_3 stack_4 stack_5 stack_6 stack_7 stack_8 stack_9 stack_10 stack_11 stack_12 stack_13 stack_14 stack_15 : UInt256}
    (hdepth : tail.length + 16 ≤ 1023)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨2⟩ (stack_0 :: stack_1 :: stack_2 :: stack_3 :: stack_4 :: stack_5 :: stack_6 :: stack_7 :: stack_8 :: stack_9 :: stack_10 :: stack_11 :: stack_12 :: stack_13 :: stack_14 :: stack_15 :: tail) mem aw rdata acc k C) :=
  evm_run h with [
      jumpdest,
      dup12Canonical,
      swap16Canonical,
      stop
    ]

evm_theorem block_6_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 : UInt256}
    (hdepth : tail.length + 1 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨6⟩ (stack_0 :: tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      jumpdest
    ])).withPC (pc' := ⟨7⟩) (by native_decide)

evm_theorem block_6_jump
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    {stack_0 : UInt256}
    (hdepth : tail.length + 1 ≤ 1024)
    (h : RDx symCheckBranchFixtureBytecode ee g s0 ⟨6⟩ (stack_0 :: tail) mem aw rdata acc k C) :=
  fun (hdec : _) (hjd : _) =>
    (block_6_body hdepth h).jump hdec hjd (by omega)

end SymCheckBranchSmoke
