-- Generated by Tools/generate_rdx_blocks.py; do not edit manually.

import Reasoning.SymCheck
import Examples.CtorStore.Bytecode

open Solm ABI Ethereum Ethereum.EVM
open Reasoning.Reach

set_option maxRecDepth 100000
set_option linter.unusedVariables false

namespace CtorStore.SymCheckSmoke

private theorem symcheckCodeMatches :
    ctorStoreRuntimeBytecode = ⟨#[0x60, 0x80, 0x60, 0x40, 0x52, 0x5f, 0x5f, 0xfd]⟩ := by native_decide

evm_theorem block_0_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1022)
    (h : RDx ctorStoreRuntimeBytecode ee g s0 ⟨0⟩ (tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      pushCanonical 1 .PUSH1 ⟨0x80⟩ (by decide),
      pushCanonical 1 .PUSH1 ⟨0x40⟩ (by decide),
      mstoreCanonical,
      push0,
      push0
    ])).withPC (pc' := ⟨7⟩) (by native_decide)

evm_theorem block_0_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1022)
    (h : RDx ctorStoreRuntimeBytecode ee g s0 ⟨0⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      pushCanonical 1 .PUSH1 ⟨0x80⟩ (by decide),
      pushCanonical 1 .PUSH1 ⟨0x40⟩ (by decide),
      mstoreCanonical,
      push0,
      push0,
      revCanonical
    ]


end CtorStore.SymCheckSmoke
