-- Generated by Tools/generate_rdx_blocks.py; do not edit manually.

import Reasoning.SymCheck
import Tools.SymCheck.Fixtures.SymCheckFixtureCode

open Solm ABI Ethereum Ethereum.EVM
open Reasoning.Reach

set_option maxRecDepth 100000
set_option linter.unusedVariables false

namespace SymCheckDeterministicTraceSmoke

private theorem symcheckCodeMatches :
    symCheckDeterministicFixtureBytecode = ⟨#[0x60, 0x01, 0x60, 0x06, 0x57, 0x00, 0x5b, 0x60, 0x0b, 0x56, 0x00, 0x5b, 0x00, 0x5b, 0x60, 0x0d, 0x56]⟩ := by native_decide

evm_theorem trace_0_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1022)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨0⟩ (tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      pushCanonical 1 .PUSH1 ⟨0x1⟩ (by decide),
      pushCanonical 1 .PUSH1 ⟨0x6⟩ (by decide),
      jumpiT (by native_decide) (by native_decide),
      jumpdest,
      pushCanonical 1 .PUSH1 ⟨0xb⟩ (by decide),
      jump (by native_decide),
      jumpdest
    ])).withPC (pc' := ⟨12⟩) (by native_decide)

evm_theorem trace_0_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1022)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨0⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      pushCanonical 1 .PUSH1 ⟨0x1⟩ (by decide),
      pushCanonical 1 .PUSH1 ⟨0x6⟩ (by decide),
      jumpiT (by native_decide) (by native_decide),
      jumpdest,
      pushCanonical 1 .PUSH1 ⟨0xb⟩ (by decide),
      jump (by native_decide),
      jumpdest,
      stop
    ]


evm_theorem trace_5_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨5⟩ (tail) mem aw rdata acc k C) :=
  (h).withPC (pc' := ⟨5⟩) (by native_decide)

evm_theorem trace_5_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨5⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      stop
    ]


evm_theorem trace_6_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1023)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨6⟩ (tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      jumpdest,
      pushCanonical 1 .PUSH1 ⟨0xb⟩ (by decide),
      jump (by native_decide),
      jumpdest
    ])).withPC (pc' := ⟨12⟩) (by native_decide)

evm_theorem trace_6_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1023)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨6⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      jumpdest,
      pushCanonical 1 .PUSH1 ⟨0xb⟩ (by decide),
      jump (by native_decide),
      jumpdest,
      stop
    ]


evm_theorem trace_11_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨11⟩ (tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      jumpdest
    ])).withPC (pc' := ⟨12⟩) (by native_decide)

evm_theorem trace_11_halt
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1024)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨11⟩ (tail) mem aw rdata acc k C) :=
  evm_run h with [
      jumpdest,
      stop
    ]


evm_theorem trace_13_body
    {ee : ExecutionEnv} {g : Sat256} {s0 : State}
    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}
    {acc : Batteries.RBSet AccountAddress compare × AccountMap}
    {k C : Nat} {tail : List UInt256}
    (hdepth : tail.length + 0 ≤ 1023)
    (h : RDx symCheckDeterministicFixtureBytecode ee g s0 ⟨13⟩ (tail) mem aw rdata acc k C) :=
  ((evm_run h with [
      jumpdest,
      pushCanonical 1 .PUSH1 ⟨0xd⟩ (by decide),
      jump (by native_decide)
    ])).withPC (pc' := ⟨13⟩) (by native_decide)


end SymCheckDeterministicTraceSmoke
