#!/usr/bin/env python3
"""Generate Lean RDx block or maximal-trace theorems from `symcheck summarize --json`.

The translator is deliberately EquiVM-specific.  SymCheck remains an untrusted,
general summary producer; Lean replays every emitted opcode through checked RDx
steppers and infers the exact post-cursor.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


GENERATED_NOTICE = "-- Generated by Tools/generate_rdx_blocks.py; do not edit manually."
LEAN_MODULE_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*")


TERMINATORS = {
    0x00: "STOP",
    0x56: "JUMP",
    0x57: "JUMPI",
    0xF3: "RETURN",
    0xFD: "REVERT",
    0xFE: "INVALID",
    0xFF: "SELFDESTRUCT",
}

TERMINATOR_STACK_INPUTS = {
    "STOP": 0,
    "JUMP": 1,
    "JUMPI": 2,
    "RETURN": 2,
    "REVERT": 2,
    "INVALID": 0,
    "SELFDESTRUCT": 1,
}

SIMPLE_STEPS = {
    "JUMPDEST": "jumpdest",
    "POP": "pop",
    "EQ": "eq",
    "LT": "lt",
    "GT": "gt",
    "SLT": "slt",
    "SGT": "sgt",
    "ADD": "add",
    "SUB": "sub",
    "AND": "and",
    "OR": "or",
    "XOR": "xor",
    "SHL": "shl",
    "SHR": "shr",
    "MUL": "mul",
    "DIV": "div",
    "MOD": "mod",
    "ADDMOD": "addmod",
    "MULMOD": "mulmod",
    "BYTE": "byte",
    "ISZERO": "iszero",
    "NOT": "not",
    "CALLVALUE": "callvalue",
    "CALLDATASIZE": "calldatasize",
    "CALLDATALOAD": "calldataload",
    "MSTORE": "mstoreCanonical",
    "MLOAD": "mloadCanonical",
    "MSTORE8": "mstore8Canonical",
    "CALLDATACOPY": "calldatacopyCanonical",
    "MCOPY": "mcopyCanonical",
}

for _n in list(range(1, 12)) + [13, 14, 15]:
    SIMPLE_STEPS[f"DUP{_n}"] = f"dup{_n}"
for _n in [12, 16]:
    SIMPLE_STEPS[f"DUP{_n}"] = f"dup{_n}Canonical"
for _n in range(1, 12):
    SIMPLE_STEPS[f"SWAP{_n}"] = f"swap{_n}"
for _n in range(12, 17):
    SIMPLE_STEPS[f"SWAP{_n}"] = f"swap{_n}Canonical"


@dataclass(frozen=True)
class Instruction:
    pc: int
    opcode: int
    size: int

    @property
    def next_pc(self) -> int:
        return self.pc + self.size


@dataclass(frozen=True)
class TraceRoot:
    start: int


@dataclass(frozen=True)
class Block:
    start: int
    target: int
    terminator: str | None


def parse_hex(value: str) -> bytes:
    text = value.removeprefix("0x").replace("_", "")
    if len(text) % 2:
        text = "0" + text
    try:
        return bytes.fromhex(text)
    except ValueError as exc:
        raise SystemExit(f"invalid bytecode hex: {exc}") from exc


def disassemble(code: bytes) -> list[Instruction]:
    result: list[Instruction] = []
    pc = 0
    while pc < len(code):
        opcode = code[pc]
        size = 1 + (opcode - 0x5F if 0x60 <= opcode <= 0x7F else 0)
        result.append(Instruction(pc, opcode, size))
        pc += size
    return result


def discover_trace_roots(code: bytes, extra_entries: list[int]) -> list[TraceRoot]:
    """Find useful theorem entry points, not execution stopping points.

    Every JUMPDEST remains independently usable by consumers.  JUMPI fallthroughs are roots too,
    because a symbolic branch helper can establish them.  A trace which starts elsewhere does not
    stop at any of these roots: SymCheck continues until control flow becomes symbolic, execution
    halts, a loop revisits a PC, or the translator reaches an unsupported RDx step.
    """
    instructions = disassemble(code)
    by_pc = {instr.pc: instr for instr in instructions}
    entries = {0} if code else set()
    entries.update(instr.pc for instr in instructions if instr.opcode == 0x5B)
    entries.update(
        instr.next_pc
        for instr in instructions
        if instr.opcode == 0x57 and instr.next_pc in by_pc
    )
    for pc in extra_entries:
        if pc not in by_pc:
            raise SystemExit(f"extra entry PC {pc} is not an instruction boundary")
        entries.add(pc)

    return [TraceRoot(start) for start in sorted(entries)]


def discover_blocks(code: bytes, extra_entries: list[int]) -> list[Block]:
    instructions = disassemble(code)
    roots = discover_trace_roots(code, extra_entries)
    entries = {root.start for root in roots}
    blocks: list[Block] = []
    for root in roots:
        target = len(code)
        terminator: str | None = None
        for instruction in instructions:
            if instruction.pc < root.start:
                continue
            if instruction.pc > root.start and instruction.pc in entries:
                target = instruction.pc
                break
            if instruction.opcode in TERMINATORS:
                target = instruction.pc
                terminator = TERMINATORS[instruction.opcode]
                break
        blocks.append(Block(root.start, target, terminator))
    return blocks


def parse_json_output(stdout: str) -> dict[str, Any]:
    for line in reversed(stdout.splitlines()):
        line = line.strip()
        if line.startswith("{"):
            try:
                value = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(value, dict):
                return value
    raise RuntimeError("SymCheck did not emit a JSON object")


def run_summary(
    exe: str, code_hex: str, start: int, target: int | None, fuel: int
) -> dict[str, Any]:
    command = [
        exe,
        "summarize",
        "--code", code_hex,
        "--pc", str(start),
        "--fuel", str(fuel),
        "--memory", "sym:memory",
        "--active-words", "var:active_words",
        "--calldata", "sym:calldata",
        "--returndata", "sym:returndata",
        "--callvalue", "var:callvalue",
        "--block-number", "var:block_number",
        "--timestamp", "var:timestamp",
        "--gas", "var:gas",
        "--json",
        "--trace-opcodes",
    ]
    if target is not None:
        command.extend(["--target-pc", str(target)])
    process = subprocess.run(command, text=True, capture_output=True, check=False)
    if process.returncode != 0:
        raise RuntimeError(
            f"SymCheck failed for trace root {start}: "
            f"{process.stderr.strip() or process.stdout.strip()}"
        )
    summary = parse_json_output(process.stdout)
    required = {
        "mode", "solverFree", "steps", "stop", "pc", "pcTrace",
        "pcTraceOpcodes", "stack", "stackTail", "initialStackDepth",
        "memory", "activeWords", "returndata", "gasCost",
    }
    missing = sorted(required.difference(summary))
    if missing:
        raise RuntimeError(f"SymCheck summary is missing fields: {', '.join(missing)}")
    if summary["mode"] != "straight-line" or summary["solverFree"] is not True:
        raise RuntimeError("SymCheck returned a non-straight-line or solver-backed summary")
    return summary


def push_step(code: bytes, pc: int, opcode_name: str) -> str | None:
    if opcode_name == "PUSH0":
        return "push0"
    match = re.fullmatch(r"PUSH(\d+)", opcode_name)
    if not match:
        return None
    width = int(match.group(1))
    if pc + 1 + width > len(code):
        return None
    payload = code[pc + 1 : pc + 1 + width]
    value = int.from_bytes(payload, "big")
    return (
        f"pushCanonical {width} .PUSH{width} ⟨0x{value:x}⟩ (by decide)"
    )


def render_step(code: bytes, entry: dict[str, Any]) -> str | None:
    pc = int(entry["pc"])
    opcode_name = str(entry["opcode"]).upper()
    pushed = push_step(code, pc, opcode_name)
    if pushed is not None:
        return pushed
    return SIMPLE_STEPS.get(opcode_name)


def render_trace_step(
    code: bytes, entry: dict[str, Any], successor_pc: int
) -> str | None:
    """Render an executed step, including locally resolved control flow."""
    opcode_name = str(entry["opcode"]).upper()
    pc = int(entry["pc"])
    if opcode_name == "JUMP":
        return "jump (by native_decide)"
    if opcode_name == "JUMPI":
        if pc >= len(code) or code[pc] != 0x57:
            return None
        if successor_pc == pc + 1:
            return "jumpiNT (by evm_branch_zero)"
        return "jumpiT (by native_decide) (by native_decide)"
    return render_step(code, entry)


def executed_entries(summary: dict[str, Any]) -> list[dict[str, Any]]:
    return list(summary["pcTraceOpcodes"][: int(summary["steps"])])


def first_revisit_step(summary: dict[str, Any]) -> int | None:
    """Return the number of steps before the first repeated program counter."""
    seen: set[int] = set()
    for index, entry in enumerate(summary.get("pcTraceOpcodes", [])):
        pc = int(entry["pc"])
        if pc in seen:
            return index
        seen.add(pc)
    return None


def opcode_name_at(code: bytes, pc: int) -> str | None:
    if pc < 0 or pc >= len(code):
        return None
    return TERMINATORS.get(code[pc])


def is_symbolic_control_boundary(opcode_name: str | None, stop: str) -> bool:
    return (
        opcode_name == "JUMP"
        and "needs a concrete value" in stop
    ) or (
        opcode_name == "JUMPI"
        and ("needs a concrete value" in stop or "needs SMT" in stop)
    )


def render_trace_steps(
    code: bytes, entries: list[dict[str, Any]], endpoint: int
) -> tuple[list[str], dict[str, Any] | None]:
    rendered: list[str] = []
    for index, entry in enumerate(entries):
        successor_pc = int(entries[index + 1]["pc"]) if index + 1 < len(entries) else endpoint
        step = render_trace_step(code, entry, successor_pc)
        if step is None:
            return rendered, entry
        rendered.append(step)
    return rendered, None


def lean_byte_array(code: bytes) -> str:
    data = ", ".join(f"0x{byte:02x}" for byte in code)
    return f"⟨#[{data}]⟩"


def binder_lines(materialized: int, max_depth: int, code_name: str, start: int) -> list[str]:
    stack_binders = ""
    if materialized:
        names = " ".join(f"stack_{idx}" for idx in range(materialized))
        stack_binders = f"    {{{names} : UInt256}}\n"
    stack = "tail"
    for idx in reversed(range(materialized)):
        stack = f"stack_{idx} :: {stack}"
    return [
        "    {ee : ExecutionEnv} {g : Sat256} {s0 : State}",
        "    {mem : ByteArray} {aw : UInt256} {rdata : ByteArray}",
        "    {acc : Batteries.RBSet AccountAddress compare × AccountMap}",
        "    {k C : Nat} {tail : List UInt256}",
        *(stack_binders.rstrip().splitlines() if stack_binders else []),
        f"    (hdepth : tail.length + {materialized} ≤ {max_depth})",
        f"    (h : RDx {code_name} ee g s0 ⟨{start}⟩ ({stack}) mem aw rdata acc k C)",
    ]


def render_theorem(
    name: str,
    code_name: str,
    start: int,
    endpoint: int,
    materialized: int,
    max_depth: int,
    steps: list[str],
) -> str:
    binders = "\n".join(binder_lines(materialized, max_depth, code_name, start))
    step_text = ",\n      ".join(steps)
    if steps:
        proof = f"(evm_run h with [\n      {step_text}\n    ])"
    else:
        proof = "h"
    return (
        f"evm_theorem {name}\n{binders} :=\n"
        f"  ({proof}).withPC (pc' := ⟨{endpoint}⟩) (by native_decide)\n"
    )


def terminal_step(terminator: str | None) -> str | None:
    return {
        "STOP": "stop",
        "RETURN": "retCanonical",
        "REVERT": "revCanonical",
        "INVALID": "raw invalid (by native_decide)",
    }.get(terminator)


def render_terminal_theorem(
    name: str,
    code_name: str,
    start: int,
    materialized: int,
    max_depth: int,
    steps: list[str],
    terminator: str,
) -> str:
    binders = "\n".join(binder_lines(materialized, max_depth, code_name, start))
    all_steps = steps + [terminal_step(terminator)]
    step_text = ",\n      ".join(step for step in all_steps if step is not None)
    return (
        f"evm_theorem {name}\n{binders} :=\n"
        f"  evm_run h with [\n      {step_text}\n    ]\n"
    )


def render_control_edge_theorems(
    body_name: str,
    code_name: str,
    start: int,
    materialized: int,
    max_depth: int,
    terminator: str | None,
    post_stack_words: int,
) -> list[tuple[str, str]]:
    """Close a body theorem over a dynamic branch.

    The body theorem deliberately leaves its post-state type inferred by Lean.  Underscore-typed
    lambda binders let the checked RDx edge theorem infer the precise decode, condition, and
    destination hypotheses from that post-state, without translating SymCheck expressions into
    Lean syntax.
    """
    binders = "\n".join(binder_lines(materialized, max_depth, code_name, start))
    consumed = TERMINATOR_STACK_INPUTS.get(terminator or "", 0)
    if post_stack_words > consumed:
        stack_bound = "by simp only [List.length_cons]; omega"
    else:
        stack_bound = "by omega"
    if terminator == "JUMP":
        name = body_name.removesuffix("_body") + "_jump"
        theorem = (
            f"evm_theorem {name}\n{binders} :=\n"
            "  fun (hdec : _) (hjd : _) =>\n"
            f"    ({body_name} hdepth h).jump hdec hjd ({stack_bound})\n"
        )
        return [(name, theorem)]
    if terminator == "JUMPI":
        base = body_name.removesuffix("_body")
        taken_name = base + "_taken"
        not_taken_name = base + "_notTaken"
        taken = (
            f"evm_theorem {taken_name}\n{binders} :=\n"
            "  fun (hdec : _) (hcondition : _) (hjd : _) =>\n"
            f"    ({body_name} hdepth h).jumpiT hdec hcondition hjd ({stack_bound})\n"
        )
        not_taken = (
            f"evm_theorem {not_taken_name}\n{binders} :=\n"
            "  fun (hdec : _) (hcondition : _) =>\n"
            f"    ({body_name} hdepth h).jumpiNT hdec hcondition ({stack_bound})\n"
        )
        return [(taken_name, taken), (not_taken_name, not_taken)]
    return []


def materialized_for_edge(summary: dict[str, Any], terminator: str | None) -> int:
    """Include tail words consumed by a terminator that the boundary summary does not execute."""
    materialized = int(summary["stackTail"]["materialized"])
    required = TERMINATOR_STACK_INPUTS.get(terminator or "", 0)
    visible = len(summary.get("stack", []))
    return materialized + max(0, required - visible)


def markdown_section(record: dict[str, Any]) -> str:
    summary = record["summary"]
    trace = ", ".join(
        f"{entry['pc']}:{entry['opcode']}" for entry in summary.get("pcTraceOpcodes", [])
    )
    is_trace = "endKind" in record
    fields = [
        (
            f"## Trace root {record['start']} → {record['endpoint']}"
            if is_trace else f"## Block {record['start']} → {record['endpoint']}"
        ),
        "",
        f"- Status: `{record['status']}`",
        (
            f"- End kind: `{record['endKind']}`"
            if is_trace else f"- Requested boundary: `{record['target']}`"
        ),
        f"- Stop: `{summary.get('stop')}`",
        f"- Steps: `{summary.get('steps')}`",
        f"- Gas cost: `{summary.get('gasCost')}`",
        f"- Trace: `{trace}`",
        f"- Stack: `{summary.get('stack')}`",
        f"- Memory: `{summary.get('memory')}`",
        f"- Active words: `{summary.get('activeWords')}`",
        f"- Returndata: `{summary.get('returndata')}`",
    ]
    if record.get("reason"):
        fields.append(f"- Incomplete reason: `{record['reason']}`")
    fields.extend(["", "<details><summary>Raw SymCheck JSON</summary>", "", "```json",
                   json.dumps(summary, indent=2, sort_keys=True), "```", "", "</details>", ""])
    return "\n".join(fields)


def chunks(items: list[str], size: int) -> list[list[str]]:
    if size <= 0:
        return [items]
    return [items[start : start + size] for start in range(0, len(items), size)]


def render_lean_module(
    imports: list[str],
    namespace: str,
    declarations: list[str],
    *,
    code_name: str | None = None,
    code: bytes | None = None,
) -> str:
    unique_imports = list(dict.fromkeys(imports))
    sections = [
        GENERATED_NOTICE,
        "\n".join(f"import {module}" for module in unique_imports),
        "open Solm ABI Ethereum Ethereum.EVM\nopen Reasoning.Reach",
        "set_option maxRecDepth 100000\nset_option linter.unusedVariables false",
        f"namespace {namespace}",
    ]
    if code_name is not None:
        if code is None:
            raise ValueError("code is required when emitting the bytecode equality check")
        sections.append(
            "private theorem symcheckCodeMatches :\n"
            f"    {code_name} = {lean_byte_array(code)} := by native_decide"
        )
    sections.extend(declarations)
    sections.append(f"end {namespace}\n")
    return "\n\n".join(section for section in sections if section)


def write_lean_catalog(
    output: Path,
    output_module: str | None,
    blocks_per_file: int,
    imports: list[str],
    namespace: str,
    code_name: str,
    code: bytes,
    declaration_groups: list[str],
    records: list[dict[str, Any]],
) -> list[Path]:
    split = blocks_per_file > 0 and len(declaration_groups) > blocks_per_file
    if not split:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(
            render_lean_module(
                imports, namespace, declaration_groups, code_name=code_name, code=code
            ),
            encoding="utf-8",
        )
        for record in records:
            record["leanFile"] = str(output)
        return [output]

    if output_module is None:
        raise SystemExit(
            f"{len(declaration_groups)} catalog entries exceed "
            f"--blocks-per-file {blocks_per_file}; "
            "provide --output-module for deterministic Lean part imports"
        )
    if output.suffix != ".lean":
        raise SystemExit("split output path must end in .lean")
    if LEAN_MODULE_RE.fullmatch(output_module) is None:
        raise SystemExit(f"invalid Lean module name for --output-module: {output_module}")

    grouped = chunks(declaration_groups, blocks_per_file)
    part_dir = output.with_suffix("")
    part_dir.mkdir(parents=True, exist_ok=True)
    width = max(3, len(str(len(grouped) - 1)))
    part_paths: list[Path] = []
    part_modules: list[str] = []
    record_index = 0
    for index, declaration_chunk in enumerate(grouped):
        suffix = f"Part{index:0{width}d}"
        part_path = part_dir / f"{suffix}.lean"
        part_module = f"{output_module}.{suffix}"
        part_path.write_text(
            render_lean_module(imports, namespace, declaration_chunk), encoding="utf-8"
        )
        part_paths.append(part_path)
        part_modules.append(part_module)
        for record in records[record_index : record_index + len(declaration_chunk)]:
            record["leanFile"] = str(part_path)
        record_index += len(declaration_chunk)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        render_lean_module(
            part_modules, namespace, [], code_name=code_name, code=code
        ),
        encoding="utf-8",
    )
    return [output, *part_paths]


def generate_block(
    exe: str,
    code: bytes,
    code_hex: str,
    code_name: str,
    block: Block,
    fuel: int,
) -> tuple[dict[str, Any], str, bool]:
    """Generate one original, single-basic-block catalog entry."""
    declarations: list[str] = []
    summary = run_summary(exe, code_hex, block.start, block.target, fuel)
    executed = executed_entries(summary)
    rendered: list[str] = []
    unsupported: dict[str, Any] | None = None
    for entry in executed:
        step = render_step(code, entry)
        if step is None:
            unsupported = entry
            break
        rendered.append(step)

    if unsupported is not None:
        endpoint = int(unsupported["pc"])
        summary = run_summary(exe, code_hex, block.start, endpoint, fuel)
        executed = executed_entries(summary)
        prefix = [render_step(code, entry) for entry in executed]
        if any(step is None for step in prefix):
            raise RuntimeError("prefix summary still contains an unsupported opcode")
        rendered = [step for step in prefix if step is not None]
        status = "incomplete"
        reason = f"unsupported RDx step at PC {endpoint}: {unsupported['opcode']}"
        theorem_name = f"block_{block.start}_prefix_{endpoint}"
    elif int(summary["pc"]) != block.target or summary["stop"] != f"target-pc {block.target}":
        endpoint = int(summary["pc"])
        status = "incomplete"
        reason = str(summary["stop"])
        theorem_name = f"block_{block.start}_prefix_{endpoint}"
    else:
        endpoint = block.target
        status = "complete"
        reason = None
        theorem_name = f"block_{block.start}_body"

    depths = summary["initialStackDepth"]
    edge_terminator = block.terminator if status == "complete" else None
    materialized = materialized_for_edge(summary, edge_terminator)
    max_depth = int(depths["maximum"])
    declarations.append(
        render_theorem(
            theorem_name, code_name, block.start, endpoint,
            materialized, max_depth, rendered,
        )
    )

    edge_names: list[str] = []
    edge_step = terminal_step(block.terminator)
    if status == "complete" and edge_step is not None:
        edge_name = f"block_{block.start}_halt"
        edge_names.append(edge_name)
        declarations.append(
            render_terminal_theorem(
                edge_name, code_name, block.start,
                materialized, max_depth, rendered, block.terminator or "",
            )
        )
    elif status == "complete":
        branch_edges = render_control_edge_theorems(
            theorem_name, code_name, block.start,
            materialized, max_depth, block.terminator,
            len(summary.get("stack", [])),
        )
        edge_names.extend(name for name, _ in branch_edges)
        declarations.extend(theorem for _, theorem in branch_edges)

    if status == "complete" and block.terminator is not None and not edge_names:
        status = "incomplete"
        reason = f"unsupported RDx terminal edge: {block.terminator}"

    record = {
        "start": block.start,
        "target": block.target,
        "endpoint": endpoint,
        "terminator": block.terminator,
        "status": status,
        "reason": reason,
        "bodyTheorem": theorem_name,
        "edgeTheorems": edge_names,
        "theoremInitialStackMaterialized": materialized,
        "theoremInitialStackMaximum": max_depth,
        "summary": summary,
    }
    return record, "\n".join(declarations), status != "complete"


def generate_trace(
    exe: str,
    code: bytes,
    code_hex: str,
    code_name: str,
    start: int,
    fuel: int,
) -> tuple[dict[str, Any], str, bool]:
    """Generate one maximal solver-free trace rooted at ``start``."""
    summary = run_summary(exe, code_hex, start, None, fuel)
    revisit_step = first_revisit_step(summary)
    end_kind: str | None = None
    if revisit_step is not None:
        # Re-run with the exact prefix length so the summary's final symbolic state is the state at
        # the first revisit, rather than an arbitrary later fuel-exhausted loop iteration.
        summary = run_summary(exe, code_hex, start, None, revisit_step)
        end_kind = "loop-revisit"

    executed = executed_entries(summary)
    endpoint = int(summary["pc"])
    terminal: str | None = None
    if executed:
        last_name = str(executed[-1]["opcode"]).upper()
        if terminal_step(last_name) is not None and int(executed[-1]["pc"]) == endpoint:
            terminal = last_name
            endpoint = int(executed[-1]["pc"])
            body_entries = executed[:-1]
            end_kind = "halt"
        else:
            body_entries = executed
    else:
        body_entries = []

    rendered, unsupported = render_trace_steps(code, body_entries, endpoint)
    if unsupported is not None:
        endpoint = int(unsupported["pc"])
        summary = run_summary(exe, code_hex, start, endpoint, fuel)
        body_entries = executed_entries(summary)
        rendered, still_unsupported = render_trace_steps(code, body_entries, endpoint)
        if still_unsupported is not None:
            raise RuntimeError("prefix summary still contains an unsupported opcode")
        terminal = None
        end_kind = "unsupported-step"
        status = "incomplete"
        reason = f"unsupported RDx step at PC {endpoint}: {unsupported['opcode']}"
    else:
        endpoint_opcode = opcode_name_at(code, endpoint)
        stop = str(summary["stop"])
        if end_kind == "halt":
            status = "complete"
            reason = None
        elif end_kind == "loop-revisit":
            status = "complete"
            reason = None
        elif is_symbolic_control_boundary(endpoint_opcode, stop):
            end_kind = "symbolic-control"
            status = "complete"
            reason = None
        else:
            end_kind = "external-boundary" if stop != "fuel exhausted" else "fuel-exhausted"
            status = "incomplete"
            reason = stop

    theorem_name = f"trace_{start}_body"
    edge_terminator = terminal
    if end_kind == "symbolic-control":
        edge_terminator = opcode_name_at(code, endpoint)
    depths = summary["initialStackDepth"]
    materialized = materialized_for_edge(summary, edge_terminator)
    max_depth = int(depths["maximum"])
    declarations = [
        render_theorem(
            theorem_name, code_name, start, endpoint,
            materialized, max_depth, rendered,
        )
    ]

    edge_names: list[str] = []
    if terminal is not None:
        edge_name = f"trace_{start}_halt"
        edge_names.append(edge_name)
        declarations.append(
            render_terminal_theorem(
                edge_name, code_name, start,
                materialized, max_depth, rendered, terminal,
            )
        )
    elif end_kind == "symbolic-control":
        branch_edges = render_control_edge_theorems(
            theorem_name, code_name, start,
            materialized, max_depth, edge_terminator,
            len(summary.get("stack", [])),
        )
        edge_names.extend(name for name, _ in branch_edges)
        declarations.extend(theorem for _, theorem in branch_edges)

    if status == "complete" and edge_terminator is not None and not edge_names:
        status = "incomplete"
        reason = f"unsupported RDx terminal edge: {edge_terminator}"

    record = {
        "start": start,
        "endpoint": endpoint,
        "endKind": end_kind,
        "status": status,
        "reason": reason,
        "bodyTheorem": theorem_name,
        "edgeTheorems": edge_names,
        "theoremInitialStackMaterialized": materialized,
        "theoremInitialStackMaximum": max_depth,
        "summary": summary,
    }
    return record, "\n".join(declarations), status != "complete"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--catalog-kind",
        choices=("blocks", "traces"),
        default="blocks",
        help=(
            "emit original basic blocks or maximal deterministic traces rooted at every "
            "JUMPDEST/fallthrough entry (default: blocks)"
        ),
    )
    parser.add_argument("--symcheck", required=True, help="path to the built symcheck executable")
    parser.add_argument("--code", required=True, help="legacy EVM bytecode as hex")
    parser.add_argument("--lean-code", required=True, help="qualified Lean ByteArray declaration")
    parser.add_argument("--lean-import", action="append", default=[], help="additional Lean import")
    parser.add_argument("--namespace", required=True, help="namespace for generated declarations")
    parser.add_argument("--output", type=Path, required=True, help="generated Lean file")
    parser.add_argument(
        "--output-module",
        help="Lean module name for --output; required when the catalog is split",
    )
    parser.add_argument(
        "--blocks-per-file",
        type=int,
        default=100,
        help="split catalogs larger than this many entries (0 disables splitting; default: 100)",
    )
    parser.add_argument("--manifest", type=Path, required=True, help="machine-readable coverage JSON")
    parser.add_argument("--summaries", type=Path, required=True, help="human-readable summary Markdown")
    parser.add_argument("--extra-entry-pc", type=int, action="append", default=[])
    args = parser.parse_args()

    if args.blocks_per_file < 0:
        parser.error("--blocks-per-file must be nonnegative")

    code = parse_hex(args.code)
    code_hex = code.hex()
    if args.catalog_kind == "blocks":
        catalog_entries: list[Block | TraceRoot] = discover_blocks(code, args.extra_entry_pc)
    else:
        catalog_entries = discover_trace_roots(code, args.extra_entry_pc)
    if args.blocks_per_file > 0 and len(catalog_entries) > args.blocks_per_file:
        if args.output_module is None:
            parser.error(
                f"{len(catalog_entries)} catalog entries exceed "
                f"--blocks-per-file {args.blocks_per_file}; "
                "--output-module is required"
            )
        if args.output.suffix != ".lean":
            parser.error("split output path must end in .lean")
        if LEAN_MODULE_RE.fullmatch(args.output_module) is None:
            parser.error(f"invalid Lean module name for --output-module: {args.output_module}")
    fuel = max(2, len(disassemble(code)) + 2)
    records: list[dict[str, Any]] = []
    declaration_groups: list[str] = []
    incomplete = False

    for entry in catalog_entries:
        if args.catalog_kind == "blocks":
            if not isinstance(entry, Block):
                raise AssertionError("block catalog contains a trace root")
            record, declarations, entry_incomplete = generate_block(
                args.symcheck, code, code_hex, args.lean_code, entry, fuel
            )
        else:
            record, declarations, entry_incomplete = generate_trace(
                args.symcheck, code, code_hex, args.lean_code, entry.start, fuel
            )
        records.append(record)
        declaration_groups.append(declarations)
        incomplete = incomplete or entry_incomplete

    imports = ["Reasoning.SymCheck", *args.lean_import]
    lean_files = write_lean_catalog(
        args.output,
        args.output_module,
        args.blocks_per_file,
        imports,
        args.namespace,
        args.lean_code,
        code,
        declaration_groups,
        records,
    )
    manifest: dict[str, Any] = {
        "formatVersion": 2 if args.catalog_kind == "blocks" else 3,
        "generator": "Tools/generate_rdx_blocks.py",
        "catalogKind": args.catalog_kind,
        "code": code_hex,
        "leanCode": args.lean_code,
        "namespace": args.namespace,
        "leanFiles": [str(path) for path in lean_files],
        "outputModule": args.output_module if len(lean_files) > 1 else None,
        "blocksPerFile": args.blocks_per_file,
        "complete": not incomplete,
    }
    if args.catalog_kind == "blocks":
        manifest["blocks"] = records
    else:
        manifest["traceRoots"] = [entry.start for entry in catalog_entries]
        manifest["traces"] = records
    catalog_description = (
        "adjacent Lean block catalog. Lean replay is authoritative for theorem conclusions."
        if args.catalog_kind == "blocks"
        else "adjacent Lean maximal-trace catalog. Lean replay is authoritative for theorem "
        "conclusions. Every JUMPDEST is a root, but it does not stop an ongoing trace."
    )
    markdown = (
        "<!-- Generated by Tools/generate_rdx_blocks.py; do not edit manually. -->\n\n"
        f"# SymCheck summaries for `{args.lean_code}`\n\n"
        "This file preserves the human-readable and raw SymCheck view used to generate the "
        + catalog_description
        + "\n\n"
        "Generated Lean files:\n\n"
        + "\n".join(f"- `{path}`" for path in lean_files)
        + "\n\n"
        + "\n".join(markdown_section(record) for record in records)
    )

    for path in (args.manifest, args.summaries):
        path.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.summaries.write_text(markdown, encoding="utf-8")

    if incomplete:
        print(f"generated catalog with incomplete {args.catalog_kind} coverage", file=sys.stderr)
        return 2
    if args.catalog_kind == "blocks":
        print(f"generated {len(records)} block theorem catalog entries")
    else:
        print(f"generated {len(records)} maximal deterministic trace entries")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
